package com.thinkgem.jeesite.modules.payment.webservice.huanxun;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-03-27T13:18:43.047+08:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://payat.ips.com.cn/WebService/TradeQuery", name = "TradeQueryService")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface TradeQueryService {

    @WebResult(name = "getIssuedByBillNoResult", targetNamespace = "http://payat.ips.com.cn/WebService/TradeQuery", partName = "getIssuedByBillNoResult")
    @WebMethod(action = "http://payat.ips.com.cn/WebService/TradeQuery/getIssuedByBillNo")
    public String getIssuedByBillNo(
            @WebParam(partName = "getIssuedByBillNo", name = "getIssuedByBillNo")
                    String getIssuedByBillNo
    );

    @WebResult(name = "posQueryResult", targetNamespace = "http://payat.ips.com.cn/WebService/TradeQuery", partName = "posQueryResult")
    @WebMethod(action = "http://payat.ips.com.cn/WebService/TradeQuery/posQuery")
    public String posQuery(
            @WebParam(partName = "posQuery", name = "posQuery")
                    String posQuery
    );

    @WebResult(name = "getIssuedRetrunInfoResult", targetNamespace = "http://payat.ips.com.cn/WebService/TradeQuery", partName = "getIssuedRetrunInfoResult")
    @WebMethod(action = "http://payat.ips.com.cn/WebService/TradeQuery/getIssuedRetrunInfo")
    public String getIssuedRetrunInfo(
            @WebParam(partName = "getIssuedRetrunInfo", name = "getIssuedRetrunInfo")
                    String getIssuedRetrunInfo
    );

    @WebResult(name = "getTradeListResult", targetNamespace = "http://payat.ips.com.cn/WebService/TradeQuery", partName = "getTradeListResult")
    @WebMethod(action = "http://payat.ips.com.cn/WebService/TradeQuery/getTradeList")
    public String getTradeList(
            @WebParam(partName = "getTradeList", name = "getTradeList")
                    String getTradeList
    );
}
